#!/bin/bash -e

proj_dir="github.com/coreos"
proj_name="etcd-ca"
proj_path=$proj_dir/$proj_name

echo $proj_path

echo "Installing Godep and cover"
go get github.com/tools/godep
go get golang.org/x/tools/cmd/cover

echo "Building Project ${proj_path}"
# Build using Godep sandbox in Godeps/_workspace
godep go build

echo "Binary is available at ./bin/etcd-ca"
mkdir -p bin
mv etcd-ca ./bin